name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  avoid-redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: cancel redundant workflows
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  helloWord:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: run javascript
        run: node index.js

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
