name: Secrets

on: 
  workflow_dispatch:
env:
  DIA_DE_LA_SEGUNDA: lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    steps:
      - name: saludo variables
        run: echo "Hola, hoy es $DIA_DE_LA_SEGUNDA ${{ vars.NOMBRE}}"
  
  saludo-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: saludo secrets
        run: echo "Saludo, ${{vars.NOMBRE}} ${{ secrets.NOMBRE}}"
